// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/meepai/serialize/bytes/protobuf/messages.proto

package com.meepai.serialize.bytes.protobuf;

public final class MessagesProto {
  private MessagesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 id = 1;
    /**
     * <code>optional int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    // optional string subject = 2;
    /**
     * <code>optional string subject = 2;</code>
     */
    boolean hasSubject();
    /**
     * <code>optional string subject = 2;</code>
     */
    java.lang.String getSubject();
    /**
     * <code>optional string subject = 2;</code>
     */
    com.google.protobuf.ByteString
        getSubjectBytes();

    // optional string label = 3;
    /**
     * <code>optional string label = 3;</code>
     */
    boolean hasLabel();
    /**
     * <code>optional string label = 3;</code>
     */
    java.lang.String getLabel();
    /**
     * <code>optional string label = 3;</code>
     */
    com.google.protobuf.ByteString
        getLabelBytes();

    // optional string from = 4;
    /**
     * <code>optional string from = 4;</code>
     */
    boolean hasFrom();
    /**
     * <code>optional string from = 4;</code>
     */
    java.lang.String getFrom();
    /**
     * <code>optional string from = 4;</code>
     */
    com.google.protobuf.ByteString
        getFromBytes();

    // optional string to = 5;
    /**
     * <code>optional string to = 5;</code>
     */
    boolean hasTo();
    /**
     * <code>optional string to = 5;</code>
     */
    java.lang.String getTo();
    /**
     * <code>optional string to = 5;</code>
     */
    com.google.protobuf.ByteString
        getToBytes();

    // optional int64 sendTime = 6;
    /**
     * <code>optional int64 sendTime = 6;</code>
     */
    boolean hasSendTime();
    /**
     * <code>optional int64 sendTime = 6;</code>
     */
    long getSendTime();
  }
  /**
   * Protobuf type {@code serial.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage
      implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }

    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              subject_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              label_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              from_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              to_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              sendTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.meepai.serialize.bytes.protobuf.MessagesProto.internal_static_serial_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.meepai.serialize.bytes.protobuf.MessagesProto.internal_static_serial_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.meepai.serialize.bytes.protobuf.MessagesProto.Message.class, com.meepai.serialize.bytes.protobuf.MessagesProto.Message.Builder.class);
    }

    public static com.google.protobuf.Parser<Message> PARSER =
        new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // optional string subject = 2;
    public static final int SUBJECT_FIELD_NUMBER = 2;
    private java.lang.Object subject_;
    /**
     * <code>optional string subject = 2;</code>
     */
    public boolean hasSubject() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string subject = 2;</code>
     */
    public java.lang.String getSubject() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          subject_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string subject = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSubjectBytes() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string label = 3;
    public static final int LABEL_FIELD_NUMBER = 3;
    private java.lang.Object label_;
    /**
     * <code>optional string label = 3;</code>
     */
    public boolean hasLabel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string label = 3;</code>
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          label_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string label = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string from = 4;
    public static final int FROM_FIELD_NUMBER = 4;
    private java.lang.Object from_;
    /**
     * <code>optional string from = 4;</code>
     */
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string from = 4;</code>
     */
    public java.lang.String getFrom() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          from_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string from = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string to = 5;
    public static final int TO_FIELD_NUMBER = 5;
    private java.lang.Object to_;
    /**
     * <code>optional string to = 5;</code>
     */
    public boolean hasTo() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string to = 5;</code>
     */
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          to_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string to = 5;</code>
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 sendTime = 6;
    public static final int SENDTIME_FIELD_NUMBER = 6;
    private long sendTime_;
    /**
     * <code>optional int64 sendTime = 6;</code>
     */
    public boolean hasSendTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 sendTime = 6;</code>
     */
    public long getSendTime() {
      return sendTime_;
    }

    private void initFields() {
      id_ = 0;
      subject_ = "";
      label_ = "";
      from_ = "";
      to_ = "";
      sendTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSubjectBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLabelBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getFromBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getToBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, sendTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSubjectBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLabelBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getFromBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getToBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, sendTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.meepai.serialize.bytes.protobuf.MessagesProto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.meepai.serialize.bytes.protobuf.MessagesProto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.meepai.serialize.bytes.protobuf.MessagesProto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.meepai.serialize.bytes.protobuf.MessagesProto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.meepai.serialize.bytes.protobuf.MessagesProto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.meepai.serialize.bytes.protobuf.MessagesProto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.meepai.serialize.bytes.protobuf.MessagesProto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.meepai.serialize.bytes.protobuf.MessagesProto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.meepai.serialize.bytes.protobuf.MessagesProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.meepai.serialize.bytes.protobuf.MessagesProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.meepai.serialize.bytes.protobuf.MessagesProto.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code serial.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.meepai.serialize.bytes.protobuf.MessagesProto.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.meepai.serialize.bytes.protobuf.MessagesProto.internal_static_serial_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.meepai.serialize.bytes.protobuf.MessagesProto.internal_static_serial_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.meepai.serialize.bytes.protobuf.MessagesProto.Message.class, com.meepai.serialize.bytes.protobuf.MessagesProto.Message.Builder.class);
      }

      // Construct using com.meepai.serialize.bytes.protobuf.MessagesProto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        subject_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        label_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        from_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        to_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        sendTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.meepai.serialize.bytes.protobuf.MessagesProto.internal_static_serial_Message_descriptor;
      }

      public com.meepai.serialize.bytes.protobuf.MessagesProto.Message getDefaultInstanceForType() {
        return com.meepai.serialize.bytes.protobuf.MessagesProto.Message.getDefaultInstance();
      }

      public com.meepai.serialize.bytes.protobuf.MessagesProto.Message build() {
        com.meepai.serialize.bytes.protobuf.MessagesProto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.meepai.serialize.bytes.protobuf.MessagesProto.Message buildPartial() {
        com.meepai.serialize.bytes.protobuf.MessagesProto.Message result = new com.meepai.serialize.bytes.protobuf.MessagesProto.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.subject_ = subject_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.label_ = label_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.from_ = from_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.to_ = to_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.sendTime_ = sendTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.meepai.serialize.bytes.protobuf.MessagesProto.Message) {
          return mergeFrom((com.meepai.serialize.bytes.protobuf.MessagesProto.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.meepai.serialize.bytes.protobuf.MessagesProto.Message other) {
        if (other == com.meepai.serialize.bytes.protobuf.MessagesProto.Message.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasSubject()) {
          bitField0_ |= 0x00000002;
          subject_ = other.subject_;
          onChanged();
        }
        if (other.hasLabel()) {
          bitField0_ |= 0x00000004;
          label_ = other.label_;
          onChanged();
        }
        if (other.hasFrom()) {
          bitField0_ |= 0x00000008;
          from_ = other.from_;
          onChanged();
        }
        if (other.hasTo()) {
          bitField0_ |= 0x00000010;
          to_ = other.to_;
          onChanged();
        }
        if (other.hasSendTime()) {
          setSendTime(other.getSendTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.meepai.serialize.bytes.protobuf.MessagesProto.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.meepai.serialize.bytes.protobuf.MessagesProto.Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 id = 1;
      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional string subject = 2;
      private java.lang.Object subject_ = "";
      /**
       * <code>optional string subject = 2;</code>
       */
      public boolean hasSubject() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string subject = 2;</code>
       */
      public java.lang.String getSubject() {
        java.lang.Object ref = subject_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          subject_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string subject = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSubjectBytes() {
        java.lang.Object ref = subject_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subject_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string subject = 2;</code>
       */
      public Builder setSubject(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        subject_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string subject = 2;</code>
       */
      public Builder clearSubject() {
        bitField0_ = (bitField0_ & ~0x00000002);
        subject_ = getDefaultInstance().getSubject();
        onChanged();
        return this;
      }
      /**
       * <code>optional string subject = 2;</code>
       */
      public Builder setSubjectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        subject_ = value;
        onChanged();
        return this;
      }

      // optional string label = 3;
      private java.lang.Object label_ = "";
      /**
       * <code>optional string label = 3;</code>
       */
      public boolean hasLabel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string label = 3;</code>
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string label = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string label = 3;</code>
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        label_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string label = 3;</code>
       */
      public Builder clearLabel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string label = 3;</code>
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        label_ = value;
        onChanged();
        return this;
      }

      // optional string from = 4;
      private java.lang.Object from_ = "";
      /**
       * <code>optional string from = 4;</code>
       */
      public boolean hasFrom() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string from = 4;</code>
       */
      public java.lang.String getFrom() {
        java.lang.Object ref = from_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string from = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFromBytes() {
        java.lang.Object ref = from_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          from_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string from = 4;</code>
       */
      public Builder setFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string from = 4;</code>
       */
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00000008);
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      /**
       * <code>optional string from = 4;</code>
       */
      public Builder setFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        from_ = value;
        onChanged();
        return this;
      }

      // optional string to = 5;
      private java.lang.Object to_ = "";
      /**
       * <code>optional string to = 5;</code>
       */
      public boolean hasTo() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string to = 5;</code>
       */
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string to = 5;</code>
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string to = 5;</code>
       */
      public Builder setTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string to = 5;</code>
       */
      public Builder clearTo() {
        bitField0_ = (bitField0_ & ~0x00000010);
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string to = 5;</code>
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        to_ = value;
        onChanged();
        return this;
      }

      // optional int64 sendTime = 6;
      private long sendTime_ ;
      /**
       * <code>optional int64 sendTime = 6;</code>
       */
      public boolean hasSendTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 sendTime = 6;</code>
       */
      public long getSendTime() {
        return sendTime_;
      }
      /**
       * <code>optional int64 sendTime = 6;</code>
       */
      public Builder setSendTime(long value) {
        bitField0_ |= 0x00000020;
        sendTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sendTime = 6;</code>
       */
      public Builder clearSendTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sendTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:serial.Message)
    }

    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:serial.Message)
  }

  public interface MessagesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .serial.Message message = 1;
    /**
     * <code>repeated .serial.Message message = 1;</code>
     */
    java.util.List<com.meepai.serialize.bytes.protobuf.MessagesProto.Message> 
        getMessageList();
    /**
     * <code>repeated .serial.Message message = 1;</code>
     */
    com.meepai.serialize.bytes.protobuf.MessagesProto.Message getMessage(int index);
    /**
     * <code>repeated .serial.Message message = 1;</code>
     */
    int getMessageCount();
    /**
     * <code>repeated .serial.Message message = 1;</code>
     */
    java.util.List<? extends com.meepai.serialize.bytes.protobuf.MessagesProto.MessageOrBuilder> 
        getMessageOrBuilderList();
    /**
     * <code>repeated .serial.Message message = 1;</code>
     */
    com.meepai.serialize.bytes.protobuf.MessagesProto.MessageOrBuilder getMessageOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code serial.Messages}
   */
  public static final class Messages extends
      com.google.protobuf.GeneratedMessage
      implements MessagesOrBuilder {
    // Use Messages.newBuilder() to construct.
    private Messages(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Messages(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Messages defaultInstance;
    public static Messages getDefaultInstance() {
      return defaultInstance;
    }

    public Messages getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Messages(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                message_ = new java.util.ArrayList<com.meepai.serialize.bytes.protobuf.MessagesProto.Message>();
                mutable_bitField0_ |= 0x00000001;
              }
              message_.add(input.readMessage(com.meepai.serialize.bytes.protobuf.MessagesProto.Message.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          message_ = java.util.Collections.unmodifiableList(message_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.meepai.serialize.bytes.protobuf.MessagesProto.internal_static_serial_Messages_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.meepai.serialize.bytes.protobuf.MessagesProto.internal_static_serial_Messages_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.meepai.serialize.bytes.protobuf.MessagesProto.Messages.class, com.meepai.serialize.bytes.protobuf.MessagesProto.Messages.Builder.class);
    }

    public static com.google.protobuf.Parser<Messages> PARSER =
        new com.google.protobuf.AbstractParser<Messages>() {
      public Messages parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Messages(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Messages> getParserForType() {
      return PARSER;
    }

    // repeated .serial.Message message = 1;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private java.util.List<com.meepai.serialize.bytes.protobuf.MessagesProto.Message> message_;
    /**
     * <code>repeated .serial.Message message = 1;</code>
     */
    public java.util.List<com.meepai.serialize.bytes.protobuf.MessagesProto.Message> getMessageList() {
      return message_;
    }
    /**
     * <code>repeated .serial.Message message = 1;</code>
     */
    public java.util.List<? extends com.meepai.serialize.bytes.protobuf.MessagesProto.MessageOrBuilder> 
        getMessageOrBuilderList() {
      return message_;
    }
    /**
     * <code>repeated .serial.Message message = 1;</code>
     */
    public int getMessageCount() {
      return message_.size();
    }
    /**
     * <code>repeated .serial.Message message = 1;</code>
     */
    public com.meepai.serialize.bytes.protobuf.MessagesProto.Message getMessage(int index) {
      return message_.get(index);
    }
    /**
     * <code>repeated .serial.Message message = 1;</code>
     */
    public com.meepai.serialize.bytes.protobuf.MessagesProto.MessageOrBuilder getMessageOrBuilder(
        int index) {
      return message_.get(index);
    }

    private void initFields() {
      message_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < message_.size(); i++) {
        output.writeMessage(1, message_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < message_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, message_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.meepai.serialize.bytes.protobuf.MessagesProto.Messages parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.meepai.serialize.bytes.protobuf.MessagesProto.Messages parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.meepai.serialize.bytes.protobuf.MessagesProto.Messages parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.meepai.serialize.bytes.protobuf.MessagesProto.Messages parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.meepai.serialize.bytes.protobuf.MessagesProto.Messages parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.meepai.serialize.bytes.protobuf.MessagesProto.Messages parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.meepai.serialize.bytes.protobuf.MessagesProto.Messages parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.meepai.serialize.bytes.protobuf.MessagesProto.Messages parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.meepai.serialize.bytes.protobuf.MessagesProto.Messages parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.meepai.serialize.bytes.protobuf.MessagesProto.Messages parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.meepai.serialize.bytes.protobuf.MessagesProto.Messages prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code serial.Messages}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.meepai.serialize.bytes.protobuf.MessagesProto.MessagesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.meepai.serialize.bytes.protobuf.MessagesProto.internal_static_serial_Messages_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.meepai.serialize.bytes.protobuf.MessagesProto.internal_static_serial_Messages_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.meepai.serialize.bytes.protobuf.MessagesProto.Messages.class, com.meepai.serialize.bytes.protobuf.MessagesProto.Messages.Builder.class);
      }

      // Construct using com.meepai.serialize.bytes.protobuf.MessagesProto.Messages.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (messageBuilder_ == null) {
          message_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          messageBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.meepai.serialize.bytes.protobuf.MessagesProto.internal_static_serial_Messages_descriptor;
      }

      public com.meepai.serialize.bytes.protobuf.MessagesProto.Messages getDefaultInstanceForType() {
        return com.meepai.serialize.bytes.protobuf.MessagesProto.Messages.getDefaultInstance();
      }

      public com.meepai.serialize.bytes.protobuf.MessagesProto.Messages build() {
        com.meepai.serialize.bytes.protobuf.MessagesProto.Messages result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.meepai.serialize.bytes.protobuf.MessagesProto.Messages buildPartial() {
        com.meepai.serialize.bytes.protobuf.MessagesProto.Messages result = new com.meepai.serialize.bytes.protobuf.MessagesProto.Messages(this);
        int from_bitField0_ = bitField0_;
        if (messageBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            message_ = java.util.Collections.unmodifiableList(message_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.message_ = message_;
        } else {
          result.message_ = messageBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.meepai.serialize.bytes.protobuf.MessagesProto.Messages) {
          return mergeFrom((com.meepai.serialize.bytes.protobuf.MessagesProto.Messages)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.meepai.serialize.bytes.protobuf.MessagesProto.Messages other) {
        if (other == com.meepai.serialize.bytes.protobuf.MessagesProto.Messages.getDefaultInstance()) return this;
        if (messageBuilder_ == null) {
          if (!other.message_.isEmpty()) {
            if (message_.isEmpty()) {
              message_ = other.message_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMessageIsMutable();
              message_.addAll(other.message_);
            }
            onChanged();
          }
        } else {
          if (!other.message_.isEmpty()) {
            if (messageBuilder_.isEmpty()) {
              messageBuilder_.dispose();
              messageBuilder_ = null;
              message_ = other.message_;
              bitField0_ = (bitField0_ & ~0x00000001);
              messageBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMessageFieldBuilder() : null;
            } else {
              messageBuilder_.addAllMessages(other.message_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.meepai.serialize.bytes.protobuf.MessagesProto.Messages parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.meepai.serialize.bytes.protobuf.MessagesProto.Messages) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .serial.Message message = 1;
      private java.util.List<com.meepai.serialize.bytes.protobuf.MessagesProto.Message> message_ =
        java.util.Collections.emptyList();
      private void ensureMessageIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          message_ = new java.util.ArrayList<com.meepai.serialize.bytes.protobuf.MessagesProto.Message>(message_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.meepai.serialize.bytes.protobuf.MessagesProto.Message, com.meepai.serialize.bytes.protobuf.MessagesProto.Message.Builder, com.meepai.serialize.bytes.protobuf.MessagesProto.MessageOrBuilder> messageBuilder_;

      /**
       * <code>repeated .serial.Message message = 1;</code>
       */
      public java.util.List<com.meepai.serialize.bytes.protobuf.MessagesProto.Message> getMessageList() {
        if (messageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(message_);
        } else {
          return messageBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .serial.Message message = 1;</code>
       */
      public int getMessageCount() {
        if (messageBuilder_ == null) {
          return message_.size();
        } else {
          return messageBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .serial.Message message = 1;</code>
       */
      public com.meepai.serialize.bytes.protobuf.MessagesProto.Message getMessage(int index) {
        if (messageBuilder_ == null) {
          return message_.get(index);
        } else {
          return messageBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .serial.Message message = 1;</code>
       */
      public Builder setMessage(
          int index, com.meepai.serialize.bytes.protobuf.MessagesProto.Message value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.set(index, value);
          onChanged();
        } else {
          messageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .serial.Message message = 1;</code>
       */
      public Builder setMessage(
          int index, com.meepai.serialize.bytes.protobuf.MessagesProto.Message.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.set(index, builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .serial.Message message = 1;</code>
       */
      public Builder addMessage(com.meepai.serialize.bytes.protobuf.MessagesProto.Message value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.add(value);
          onChanged();
        } else {
          messageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .serial.Message message = 1;</code>
       */
      public Builder addMessage(
          int index, com.meepai.serialize.bytes.protobuf.MessagesProto.Message value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.add(index, value);
          onChanged();
        } else {
          messageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .serial.Message message = 1;</code>
       */
      public Builder addMessage(
          com.meepai.serialize.bytes.protobuf.MessagesProto.Message.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.add(builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .serial.Message message = 1;</code>
       */
      public Builder addMessage(
          int index, com.meepai.serialize.bytes.protobuf.MessagesProto.Message.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.add(index, builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .serial.Message message = 1;</code>
       */
      public Builder addAllMessage(
          java.lang.Iterable<? extends com.meepai.serialize.bytes.protobuf.MessagesProto.Message> values) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          super.addAll(values, message_);
          onChanged();
        } else {
          messageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .serial.Message message = 1;</code>
       */
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          message_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          messageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .serial.Message message = 1;</code>
       */
      public Builder removeMessage(int index) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.remove(index);
          onChanged();
        } else {
          messageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .serial.Message message = 1;</code>
       */
      public com.meepai.serialize.bytes.protobuf.MessagesProto.Message.Builder getMessageBuilder(
          int index) {
        return getMessageFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .serial.Message message = 1;</code>
       */
      public com.meepai.serialize.bytes.protobuf.MessagesProto.MessageOrBuilder getMessageOrBuilder(
          int index) {
        if (messageBuilder_ == null) {
          return message_.get(index);  } else {
          return messageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .serial.Message message = 1;</code>
       */
      public java.util.List<? extends com.meepai.serialize.bytes.protobuf.MessagesProto.MessageOrBuilder> 
           getMessageOrBuilderList() {
        if (messageBuilder_ != null) {
          return messageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(message_);
        }
      }
      /**
       * <code>repeated .serial.Message message = 1;</code>
       */
      public com.meepai.serialize.bytes.protobuf.MessagesProto.Message.Builder addMessageBuilder() {
        return getMessageFieldBuilder().addBuilder(
            com.meepai.serialize.bytes.protobuf.MessagesProto.Message.getDefaultInstance());
      }
      /**
       * <code>repeated .serial.Message message = 1;</code>
       */
      public com.meepai.serialize.bytes.protobuf.MessagesProto.Message.Builder addMessageBuilder(
          int index) {
        return getMessageFieldBuilder().addBuilder(
            index, com.meepai.serialize.bytes.protobuf.MessagesProto.Message.getDefaultInstance());
      }
      /**
       * <code>repeated .serial.Message message = 1;</code>
       */
      public java.util.List<com.meepai.serialize.bytes.protobuf.MessagesProto.Message.Builder> 
           getMessageBuilderList() {
        return getMessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.meepai.serialize.bytes.protobuf.MessagesProto.Message, com.meepai.serialize.bytes.protobuf.MessagesProto.Message.Builder, com.meepai.serialize.bytes.protobuf.MessagesProto.MessageOrBuilder> 
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          messageBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.meepai.serialize.bytes.protobuf.MessagesProto.Message, com.meepai.serialize.bytes.protobuf.MessagesProto.Message.Builder, com.meepai.serialize.bytes.protobuf.MessagesProto.MessageOrBuilder>(
                  message_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        return messageBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:serial.Messages)
    }

    static {
      defaultInstance = new Messages(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:serial.Messages)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_serial_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serial_Message_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_serial_Messages_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serial_Messages_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n@src/main/java/com/meepai/serialize/byt" +
      "es/protobuf/messages.proto\022\006serial\"a\n\007Me" +
      "ssage\022\n\n\002id\030\001 \001(\005\022\017\n\007subject\030\002 \001(\t\022\r\n\005la" +
      "bel\030\003 \001(\t\022\014\n\004from\030\004 \001(\t\022\n\n\002to\030\005 \001(\t\022\020\n\010s" +
      "endTime\030\006 \001(\003\",\n\010Messages\022 \n\007message\030\001 \003" +
      "(\0132\017.serial.MessageB4\n#com.meepai.serial" +
      "ize.bytes.protobufB\rMessagesProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_serial_Message_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_serial_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_serial_Message_descriptor,
              new java.lang.String[] { "Id", "Subject", "Label", "From", "To", "SendTime", });
          internal_static_serial_Messages_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_serial_Messages_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_serial_Messages_descriptor,
              new java.lang.String[] { "Message", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
